# Site
repository: ncide/ncide.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Eric Kaiko
title: Service and Help Desk Technical Support
email: erickaiko@gmail.com
website: www.linkedin.com/in/eric-kai/

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  ncide
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: ihaarp
linkedin_username: eric-kai
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Telegram
  icon: fas fa-telegram
  url: t.me/ncide
# - title: Telegram
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi my names's Eric, 31 years old, was born and lived my whole life in Minsk, Belarus. Relocated to Poland since April 2022, because I don't support the aggressive tone of Belarusian government. I was afraid of possible reprisals that could follow due to the fact that my political views were completely opposite to the dictatorial regime.

  PC user since 1999, yep I was only 8y.o when I first installed Win98, because I wasn't enjoying Win95 that much.

  2007 When I was 17, me and my friend managed to build 60+ PC local lan <mark>network</mark> and it was operating for almost 2 years flawlessly before new law came out that banned local networks in multi apartment buildings. At that same time I had my own <mark>server</mark> with Mu Online, Korean Diablo-inspired MMORPG.
  I am most skilled in: <mark>TroubleShooting</mark> and <mark>Windows Administration</mark>

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Wargaming
        link: wargaming.net
        # link_text: wargaming.net
        sub_title: Technical and later Financial Support Specialist
        caption: April 2011 - October 2012
        quote: >
          Let's Battle
        description: | # this will include new lines to allow paragraphs
            Worked as a productive and positive team member to test, report, support resolution of in-game technical and financial issues of a clients.
            Helped with content migration from the old community hub to a new one.
            Updating <mark>Confluence</mark> knowledge databases to help other support members resolve known issues.
            Creating support guides for support newcomers.

  - title: 
    layout: list
    content:
      - layout: left
        title: Starway Tablets
        link: www.hit-trade.by
        # link_text: www.hit-trade.by
        sub_title: Project Manager
        caption: February 2013 - June 2014
        description: |
            Collaborated with other team members to create fresh brand ideas and project initiatives.
            
            Selecting and inspecting product samples from manufacture, that is going to get into mass production.
            
            Active interaction with programmers to make changes in products firmware and UI
            
            Testing and suggesting changes into hardware part of the products.
            
            Setting up customer support and warranty environment.
            
  - title: 
    layout: list
    content:
      - layout: left
        title: MOVIE PARK
        link: www.movieparkpro.com
        # link_text: www.movieparkpro.com
        sub_title: Second Assistant Camera, Videographer
        caption: June 2014 - October 2015
        description: |
            Second Camera operator, shooting wedding footages and other events involving large groups of people festivals, parades etc.
            Video editing and postprocessing, colorcorrection.
            
  - title: 
    layout: list
    content:
      - layout: left
        title: Freelance
        sub_title: Wedding Photographer
        caption: October 2015 - Novemver 2018
        description: |
            Taking high quality wedding photographs both film and digital.
            
  - title: 
    layout: list
    content:
      - layout: left
        tittle: Freelance
        sub_title: Fashion and Portrait Photographer
        caption: Dec 2018 - December 2019
        description: |
            Taking pictures of model tests.
            
            Editorial stories for magazines.
            
  - title: 
    layout: list
    content:
      - layout: left
        title: Nikofirm
        link: nikofirm.by
        # link_text: www.movieparkpro.com
        sub_title: Fashion Photographer
        caption: February 2020 - February 2021
        description: |
            Shooting lookbooks and editorials for company products.
            
            Product photography.
            
            You can even see me for a brief moment on their intro video on their webpage.
            
  - title: 
    layout: list
    content:
      - layout: left
        title: Shoes Group
        sub_title: Fashion Photographer
        caption: January 2022 - April 2022
        description: |
            Full-time lookbook and e-commerce photography.
            
            Product photography.
            
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Minsk Institute of Management (Minsk Innovation University)
        caption: 2009 - 2013
        sub_title: Finance and Credit
        quote: >
          The University was founded in 1991. Its founder is Nikolay Vasilyevich Susha, Grand PhD in Economics, Professor, who is also the permanent rector of the University. During those and subsequent years all conditions for training highly qualified specialists in the fields of economics, law, psychology, foreign languages and information technologies were created in the University.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt lots of social and softskills that have I have taken through my career such as teamwork and working to tight deadlines.

          I spent a lot of my free time doing in-depth researches on the topics I was interested the most.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and new technologies (I was always quick with trying new software and it's new fantastic features) some of my other interests and hobbies are:
      - Marathon Cycling
      - Hiking
      - Gaming
      - Photography
      - Progressive and Classic Rock Music

      Some of my photographs on Behance 
      ![photographs](https://www.behance.net/HAARP "photographs")

  - title:
    layout: list
    content:
      -layout: left
      title: Bazzinganator
      link: bazzinaga.net
      sub_title: Bazzzzzzzzzzzzzzzzinga

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
