# Site
repository: ncide/ncide.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Eric Kaiko
title: Service and Help Desk Technical Support
email: erickaiko@gmail.com
website: www.linkedin.com/in/eric-kai/

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  ncide
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: ihaarp
linkedin_username: eric-kai
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi my names's Eric, 31 years old, was born and lived my whole life in Minsk, Belarus. Relocated to Poland since April 2022, because I don't support the aggressive tone of Belarusian government. I was afraid of possible reprisals that could follow due to the fact that my political views were completely opposite to the dictatorial regime.

  PC user since 1999, yep I was only 8y.o when I first installed Win98, because I wasn't enjoying Win95 that much.

  2007 When I was 17, me and my friend managed to build 60+ PC local lan <mark>network</mark> and it was operating for almost 2 years flawlessly before new law came out that banned local networks in multi apartment buildings. At that same time I had my own <mark>server</mark> with Mu Online, Korean Diablo-inspired MMORPG.
  I am most skilled in: <mark>TroubleShooting</mark> and <mark>Windows Administration</mark>

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Wargaming
        link: wargaming.net
        # link_text: wargaming.net
        sub_title: Technical and later Financial Support Specialist
        caption: April 2011 - October 2012
        quote: >
          Let's Battle
        description: | # this will include new lines to allow paragraphs
            Worked as a productive and positive team member to test, report, support resolution of in-game technical and financial issues of a clients.
            Helped with content migration from the old community hub to a new one.
            Updating <mark>Confluence</mark> knowledge databases to help other support members resolve known issues.
            Creating support guides for support newcomers.
 
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Harvard University
        caption: 2010 - 2013
        sub_title: BSc Computer Science
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
